"""create match analysis table

Revision ID: ceab816de2bd
Revises: 79cfdc3bdbe1
Create Date: 2026-06-25 13:12:34.359111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceab816de2bd'
down_revision: Union[str, Sequence[str], None] = '79cfdc3bdbe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('strong_matches', sa.JSON(), nullable=False),
    sa.Column('missing_skills', sa.JSON(), nullable=False),
    sa.Column('resume_suggestions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_analysis_id'), 'match_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_match_analysis_job_id'), 'match_analysis', ['job_id'], unique=False)
    op.create_index(op.f('ix_match_analysis_resume_id'), 'match_analysis', ['resume_id'], unique=False)
    op.create_index(op.f('ix_match_analysis_user_id'), 'match_analysis', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_analysis_user_id'), table_name='match_analysis')
    op.drop_index(op.f('ix_match_analysis_resume_id'), table_name='match_analysis')
    op.drop_index(op.f('ix_match_analysis_job_id'), table_name='match_analysis')
    op.drop_index(op.f('ix_match_analysis_id'), table_name='match_analysis')
    op.drop_table('match_analysis')
    # ### end Alembic commands ###
